# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "sudo fry rolls"
tagline:          "/* Son Pham's Team Spring Roll dev journal */"
description:      "Son Pham's journal and commentaries about Team Spring Roll's challenges and the fun we have solving them"
url:              http://famanson.github.io

author:
  name:           'Son Pham'
  url:            http://famanson.com

paginate:         5

# Custom vars
version:          1.0.0

link:
  team:           https://famanson.github.io/spring-roll
  personal:       http://famanson.com
