# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "sudo fry rolls"
tagline:          "/* This blog is actually mobile-friendly! */"
description:      "I write about life, code and my adventures as a software engineer"
url:              http://blog.famanson.com

author:
  name:           'Son Pham'
  url:            http://famanson.com

paginate:         5

link:
  personal:       http://famanson.com
  pdf:            /public/cv/SonPhamCV.pdf

facebook:
  appId:          409464975807064