# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "sudo fry rolls"
tagline:          "/* Would you kindly read this? */"
description:      "I write about life, code and my adventures as a software engineer"
url:              http://blog.famanson.com

author:
  name:           'Son Pham'
  url:            http://famanson.com

paginate:         5

link:
  team:           https://famanson.github.io/spring-roll
  personal:       http://famanson.com

facebook:
  appId:          409464975807064